### ISSUE TITLE
Non deterministic verification error: "Comparison might panic"

### ISSUE THREAD

**Issue by LinoTelschow** [viperproject/gobra#375]
When I try to verify the `dataplane.gobra` file of the VerifiedSCION code base (PR: https://github.com/jcp19/VerifiedSCION/pull/45), then I run in some non-deterministic behavior of Gobra.

In some cases the verification fails with hundreds of "Comparison might panic" errors.
For example see this CI test result: https://github.com/jcp19/VerifiedSCION/runs/4418824266?check_suite_focus=true

The problem only occurs with go's `error` interface and if I verify the whole `dataplane.gobra` file.
If I verify each method in isolation, then the error doesn't occur.

**Comment by jcp19** [comment]
The link to the CI test result is now broken. I speculate that this issue had to do with us not limiting the scope of quantifiers (specially in large methods) and relying too much on the auto-generated triggers in the early versions of VerifiedSCION. This problem has not been observable for quite a while, specially since we switched to the new versions of SCION, so I will close it.
